/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2024-11-13 11:15:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class About_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"ISO-8859-1\">\n");
      out.write("    <title>About Us - Find Your Roomie</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\n");
      out.write("    <style>\n");
      out.write("        /* General Body Styling */\n");
      out.write("        body {\n");
      out.write("            font-family: 'Arial', sans-serif;\n");
      out.write("            background-color: #008080; /* Light Gray */\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Container for the About Section */\n");
      out.write("        .about-container {\n");
      out.write("            width: 80%;\n");
      out.write("            max-width: 900px;\n");
      out.write("            margin: 3rem auto;\n");
      out.write("            background-color: #FFFFFF; /* White */\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\n");
      out.write("            padding: 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Title Styling */\n");
      out.write("        .about-container h1 {\n");
      out.write("            font-size: 2.5rem;\n");
      out.write("            color: #008080; /* Teal */\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Subheading Styling */\n");
      out.write("        .about-container h2 {\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            color: #FFA500; /* Orange */\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Paragraph Styling */\n");
      out.write("        .about-container p {\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            line-height: 1.8;\n");
      out.write("            color: #495057;\n");
      out.write("            text-align: justify;\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Founders Section Styling */\n");
      out.write("        .founders-section {\n");
      out.write("            margin-top: 2rem;\n");
      out.write("            padding-top: 1rem;\n");
      out.write("            border-top: 1px solid #D3D3D3; /* Light Gray Border */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .founder {\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            color: #495057;\n");
      out.write("            margin-bottom: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .founder h3 {\n");
      out.write("            font-size: 1.4rem;\n");
      out.write("            color: #008080; /* Teal */\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive Layout for Smaller Screens */\n");
      out.write("        @media screen and (max-width: 768px) {\n");
      out.write("            .about-container {\n");
      out.write("                width: 90%;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Close Button Styling */\n");
      out.write("        .btn-close {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 20px;\n");
      out.write("            left: 20px;\n");
      out.write("            width: 30px;\n");
      out.write("            height: 30px;\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            background-color: #E6D33D; /* Yellow */\n");
      out.write("            border: none;\n");
      out.write("            color: #FFFFFF; /* White */\n");
      out.write("            border-radius: 50%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-close:hover {\n");
      out.write("            background-color: #FFA500; /* Orange */\n");
      out.write("            color: #FFFFFF;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Close Button -->\n");
      out.write("    <button type=\"button\" class=\"btn-close\" aria-label=\"Close\" onclick=\"window.location.href='home.html';\">&times;</button>\n");
      out.write("\n");
      out.write("    <div class=\"about-container\">\n");
      out.write("        <h1>About Find Your Roomie</h1>\n");
      out.write("\n");
      out.write("        <h2>Our Mission</h2>\n");
      out.write("        <p>\n");
      out.write("            Find Your Roomie is a platform designed to make the process of finding a compatible roommate quick and easy. \n");
      out.write("            We connect people based on shared preferences and needs, making the roomie search simple and hassle-free.\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("        <p>\n");
      out.write("            Whether you're a student or a working professional, we provide personalized roomie suggestions to ensure a good fit. \n");
      out.write("            Our goal is to help you find a safe, comfortable, and convenient place to stay.\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("        <h2>Meet the Founders</h2>\n");
      out.write("        <div class=\"founders-section\">\n");
      out.write("            <div class=\"founder\">\n");
      out.write("                <h3>Ishita Verma</h3>\n");
      out.write("                <p>Founder and visionary behind Find Your Roomie, focused on creating a platform that makes finding roommates easier.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"founder\">\n");
      out.write("                <h3>Ishani Sharma</h3>\n");
      out.write("                <p>Technical lead, responsible for the development and smooth functionality of the platform.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"founder\">\n");
      out.write("                <h3>Sanjana Mehta</h3>\n");
      out.write("                <p>Creative head behind the user interface design, ensuring a pleasant and intuitive experience for users.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
